# Generated by Django 4.2.28 on 2026-02-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("training", "Antrenmana Katılım"),
                            ("analysis", "Analize Katılım"),
                            ("match_watching", "Maç İzleme"),
                            ("other_team_frisbee", "Farklı Takım Frizbi Antrenmanı"),
                            ("upper_body", "Üst Vücut Antrenmanı"),
                            ("lower_body_core_hiit", "Alt Vücut / Core / HIIT"),
                            ("endurance", "Koşu / Bisiklet / Patlayıcı Kuvvet"),
                            ("other_sport", "Farklı Spor"),
                            ("flexibility", "Yoga / Pilates / Mobilite"),
                            ("hf_disk", "HF Disk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("total_points", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("total_points", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color_code", models.CharField(default="#FF0000", max_length=7)),
                (
                    "captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captained_teams",
                        to="tracker.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="tracker.season",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "season")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("training", "Antrenmana Katılım"),
                            ("analysis", "Analize Katılım"),
                            ("match_watching", "Maç İzleme"),
                            ("other_team_frisbee", "Farklı Takım Frizbi Antrenmanı"),
                            ("upper_body", "Üst Vücut Antrenmanı"),
                            ("lower_body_core_hiit", "Alt Vücut / Core / HIIT"),
                            ("endurance", "Koşu / Bisiklet / Patlayıcı Kuvvet"),
                            ("other_sport", "Farklı Spor"),
                            ("flexibility", "Yoga / Pilates / Mobilite"),
                            ("hf_disk", "HF Disk"),
                        ],
                        max_length=50,
                    ),
                ),
                ("required_count", models.PositiveIntegerField(default=1)),
                ("min_points", models.PositiveIntegerField(default=0)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_goals",
                        to="tracker.season",
                    ),
                ),
            ],
            options={
                "ordering": ["season", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Bekliyor"),
                            ("responded", "Yanıtlandı"),
                            ("expired", "Süresi Doldu"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("bonus_awarded", models.BooleanField(default=False)),
                ("penalty_applied", models.BooleanField(default=False)),
                (
                    "responding_activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tag_response",
                        to="tracker.activity",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tracker.season",
                    ),
                ),
                (
                    "tagged",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_received",
                        to="tracker.player",
                    ),
                ),
                (
                    "tagger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_sent",
                        to="tracker.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="season",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_seasons",
                to="tracker.team",
            ),
        ),
        migrations.CreateModel(
            name="PointAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("weekly_goal_bonus", "Haftalık Hedef Bonusu"),
                            ("weekly_penalty", "Haftalık Ceza (10 puan altı)"),
                            ("tag_bonus", "Meydan Okuma Yanıtı Bonusu"),
                            ("tag_penalty", "Meydan Okuma Cezası"),
                            ("manual", "Manuel Düzeltme"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("week_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="tracker.player",
                    ),
                ),
                (
                    "related_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.tag",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="tracker.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tracker.player",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tracker.season",
            ),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_points", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "season")},
            },
        ),
    ]
