# Generated by Django 4.2.28 on 2026-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="color_code",
            field=models.CharField(
                choices=[("#8C1C2C", "Bordo"), ("#F5EAED", "Beyaz")],
                default="#8C1C2C",
                max_length=7,
            ),
        ),
    ]
