# Generated by Django 4.2.28 on 2026-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_team_color_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("training", "Antrenmana Katılım"),
                    ("analysis", "Analize Katılım"),
                    ("match_watching", "Maç İzleme"),
                    ("other_team_frisbee", "Farklı Takım Frizbi Antrenmanı"),
                    ("upper_body", "Üst Vücut Antrenmanı"),
                    ("lower_body_core_hiit", "Alt Vücut / Core / HIIT"),
                    ("endurance", "Koşu / Bisiklet / Patlayıcı Kuvvet"),
                    ("other_sport", "Farklı Spor"),
                    ("flexibility", "Yoga / Pilates / Mobilite"),
                    ("hf_disk", "HF Disk"),
                    ("tournament", "Turnuva Katılımı"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="weeklygoal",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("training", "Antrenmana Katılım"),
                    ("analysis", "Analize Katılım"),
                    ("match_watching", "Maç İzleme"),
                    ("other_team_frisbee", "Farklı Takım Frizbi Antrenmanı"),
                    ("upper_body", "Üst Vücut Antrenmanı"),
                    ("lower_body_core_hiit", "Alt Vücut / Core / HIIT"),
                    ("endurance", "Koşu / Bisiklet / Patlayıcı Kuvvet"),
                    ("other_sport", "Farklı Spor"),
                    ("flexibility", "Yoga / Pilates / Mobilite"),
                    ("hf_disk", "HF Disk"),
                    ("tournament", "Turnuva Katılımı"),
                ],
                max_length=50,
            ),
        ),
    ]
