# Generated by Django 4.2.28 on 2026-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_activity_activity_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["player", "season", "date"],
                name="tracker_act_player__f367ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["season", "-created_at"], name="tracker_act_season__04c32c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointadjustment",
            index=models.Index(
                fields=["player", "season", "week_number"],
                name="tracker_poi_player__f071cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["status", "expires_at"], name="tracker_tag_status_e74fb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tagged", "season", "status"],
                name="tracker_tag_tagged__ef1066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tagger", "season", "status"],
                name="tracker_tag_tagger__f074fd_idx",
            ),
        ),
    ]
