# Generated by Django 4.2.28 on 2026-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_activity_tracker_act_player__f367ad_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pointadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reason", "weekly_goal_bonus")),
                fields=("player", "season", "week_number"),
                name="uniq_weekly_goal_bonus_per_week",
            ),
        ),
    ]
